#!/bin/sh
set -e
case "$1" in
    configure)
        update-alternatives --install /usr/bin/opentenbase-psql opentenbase-psql /usr/lib/opentenbase/bin/psql 50
        update-alternatives --install /usr/bin/opentenbase-pg_dump opentenbase-pg_dump /usr/lib/opentenbase/bin/pg_dump 50
        update-alternatives --install /usr/bin/opentenbase-pg_restore opentenbase-pg_restore /usr/lib/opentenbase/bin/pg_restore 50
        ;;
esac

#DEBHELPER#

exit 0
