# OpenTenBase main control configuration
# Sourced by /usr/bin/opentenbase-ctl

ENABLED_NODES="gtm dn1 coord"

OTB_USER="opentenbase"
OTB_GROUP="opentenbase"
OTB_HOME="/usr/lib/opentenbase"

GTM_PGDATA="/var/lib/opentenbase/gtm"
GTM_PORT=6666
GTM_LOG="/var/log/opentenbase/gtm.log"

COORD_PGDATA="/var/lib/opentenbase/coord"
COORD_PORT=5432
COORD_NODENAME="coord1"
COORD_LOG="/var/log/opentenbase/coord.log"

DN1_PGDATA="/var/lib/opentenbase/dn1"
DN1_PORT=15432
DN1_NODENAME="dn001"
DN1_LOG="/var/log/opentenbase/dn1.log"
COORD_FORWARD_PORT=6669
DN1_FORWARD_PORT=6670
COORD_POOLER_PORT=6667
DN1_POOLER_PORT=6668

START_ORDER="gtm coord dn1"
STOP_ORDER="coord dn1 gtm"
