# 分布式集群配置: 1GTM + 1CN + 2DN
[instance]
name=opentenbase_cluster
type=distributed
package=/data/opentenbase/opentenbase-5.0-aarch64.tar.gz

# GTM 节点
[gtm]
master=172.20.0.2

# 协调节点
[coordinators]
master=172.20.0.3
nodes-per-server=1
conf=/data/opentenbase/postgres.conf

# 数据节点
[datanodes]
master=172.20.0.4,172.20.0.5
nodes-per-server=1
conf=/data/opentenbase/postgres.conf

[server]
ssh-user=opentenbase
ssh-password=opentenbase
ssh-port=22

[log]
level=DEBUG
